[project]
name = "arc-agi-demo"
version = "0.1.0"
requires-python = ">=3.10"
dependencies = [
    "arc-agi[all]",
    "ipykernel>=6.29.5",
    "numpy>=2.2.4",
]

[tool.uv.sources]
arc-agi = { workspace = true }
